SINGULAL_VALUE_DECOMPOSITION

In [1]:
import torch
import numpy as np 
_=torch.manual_seed(0)

In [4]:
d,k=10,10
#so this is the efficient way we can generate rank_deficient matrix
W_rank=3
W=torch.randn(d,W_rank)@ torch.randn(W_rank,k)
print(W)

tensor([[ 4.2487e+00,  1.5825e+00, -1.2685e+00, -1.4282e-02, -4.1585e-02,
         -4.6723e-01,  7.0073e-01,  4.5244e-01,  5.9456e-01, -7.0175e-01],
        [-4.2569e+00, -9.3086e-01, -1.9830e+00,  3.5119e+00, -1.8117e+00,
         -3.6012e+00,  2.6573e-01, -1.7692e+00,  2.9592e+00,  4.8613e+00],
        [ 1.4225e+00,  6.1633e-02,  4.9506e-01, -9.4286e-01,  6.8647e-01,
          1.4903e+00,  1.0352e-01,  1.0647e+00, -7.6000e-01, -1.3699e+00],
        [-1.4678e+00, -1.0089e+00, -2.4142e-01,  8.4236e-01,  6.6895e-04,
          3.6169e-01,  2.6141e-01,  7.1373e-01,  6.3386e-01,  1.1965e+00],
        [ 5.7512e-01,  1.2515e-01,  7.7555e-01, -1.0382e+00,  4.7059e-01,
          9.4334e-01, -2.3796e-01,  2.5022e-01, -9.7077e-01, -1.3200e+00],
        [ 1.6539e+00,  2.2438e-01, -9.4559e-01,  5.6617e-01,  2.7365e-02,
          9.9351e-02,  6.4995e-01,  9.1590e-01,  8.0297e-01,  3.7304e-01],
        [-9.6855e-01,  1.3232e-01,  5.7411e-01, -4.0125e-01, -1.7140e-01,
         -5.0233e-01, -5.2142e-0

In [5]:
#lets see the rank of the matrix 
W_rank=np.linalg.matrix_rank(W)
print(f"Rank of matrix W:{W_rank}")

Rank of matrix W:3


# LETS COMPUTE SVD COMPOSITION

In [8]:
U,S,V=torch.svd(W)
U_r=U[:,:W_rank]
S_r=torch.diag(S[:W_rank])
V_r=V[:,:W_rank].t()

#   compute c=U_r *S_r and R=v_r
B=U_r @S_r
A=V_r
print(f"shape of B:{B.shape}")
print(f"shape of A:{A.shape}")

shape of B:torch.Size([10, 3])
shape of A:torch.Size([3, 10])


In [10]:
#Generate random bias and input
bias=torch.randn(d)
x=torch.randn(d)
#lets now compute the y
y=W @ x+bias
y_prime=(B@A)@x+bias 
print(y)
print(y_prime)

tensor([-4.4895,  9.1701, -6.1757,  2.3967, -4.8664, -1.6132,  1.9080, -4.3373,
         2.0090, -1.8921])
tensor([-4.4895,  9.1701, -6.1757,  2.3967, -4.8664, -1.6132,  1.9080, -4.3373,
         2.0090, -1.8921])


In [11]:
print(f"here the total parameters :{W.nelement()}")
print(f"here the total parameters :{A.nelement()+A.nelement()}")

here the total parameters :100
here the total parameters :60
